platform :ios, '9.0'
target 'jhzxProject' do
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDAutoLayout', '~> 2.1.3'
#pod 'NIMSDK', '~> 3.7.0'
pod 'YTKNetwork'
pod 'SDWebImage', '~>3.8'

end
